# 理解 shape, stride, storage, view，is_contiguous 和 reshape 操作

https://zhuanlan.zhihu.com/p/2027415418696902203

In [2]:
a = [1.0, 2.0, 1.0]

In [3]:
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [5]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6) # <1>
print(points)
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0


tensor([0., 0., 0., 0., 0., 0.])


In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])

## Storage

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_12732\3297796694.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

In [20]:
points.storage()[1]

1.0

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

In [25]:
points.stride()

(2, 1)

In [26]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [27]:
second_point.storage_offset()

2

## Stride

In [28]:
second_point.stride()

(1,)

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [33]:
id(points.storage()) == id(points_t.storage())

True

In [34]:
points.stride()

(2, 1)

In [35]:
points_t.stride()

(1, 2)

In [36]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [37]:
transpose_t.shape

torch.Size([5, 4, 3])

In [38]:
some_t.stride()

(20, 5, 1)

In [39]:
transpose_t.stride()

(1, 5, 20)

In [40]:
points.is_contiguous()

True

In [41]:
points_t.is_contiguous()

False

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [43]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [44]:
points_t.stride()

(1, 2)

In [45]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t_cont.stride()

(3, 1)

In [47]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [49]:
short_points.dtype

torch.int16

In [50]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [51]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [52]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [53]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [54]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [55]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [57]:
points = torch.from_numpy(points_np)

In [58]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [59]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [60]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [61]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [62]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [63]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [64]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [65]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [66]:
points_gpu = points.to(device='cuda')

In [67]:
points_gpu = points.to(device='cuda:0')

In [68]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [69]:
points_gpu = points_gpu + 4

In [70]:
points_cpu = points_gpu.to(device='cpu')

In [71]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [72]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [73]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [74]:
a = torch.ones(3, 2)

In [75]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

# 索引 indexing
Tensor 的索引类似于 Python List 的索引和分片。

比如一个 AxBxC 的三个维度的 Tensor a。

a[第0维的分片, 第1维的分片, 第2维的分片]

分片的语法和 Python List 分片语法一致，开始:结束:步进。

更多索引的[高级语法介绍](https://medium.com/@AI-Simplified/mastering-pytorch-indexing-simple-techniques-with-practical-examples-154c232b6d84)。

In [78]:
print("*" * 8, " a")
a = torch.randn(5,4,3)
print(a)

print("*" * 8, " b")
b = a[1,]     # 只要第 0 维的第一个成员
print(b)

print("*" * 8, " c")
c = a[1:]   # 第 0 维从第一个成员开始都要，注意：这里索引从 0 开始
print(c)

print("*" * 8, " d")
d = a[1:, 1] # 第 0 维从第一个成员开始都要，第二维只要第一个成员
print(d)

********  a
tensor([[[-0.5605,  0.7492,  0.8745],
         [-0.0352,  1.5848, -0.3735],
         [ 0.6052,  0.5956,  0.4227],
         [ 1.3597,  0.9243,  1.1799]],

        [[-0.0808, -0.4589,  0.4824],
         [-0.2722, -0.1824, -1.2119],
         [ 1.0293,  1.0540,  0.2618],
         [ 1.5752,  0.0859, -1.9145]],

        [[-1.9635, -0.7759,  0.5267],
         [ 1.5830,  1.7170, -0.6148],
         [ 1.1058,  1.1292,  0.7002],
         [-2.2133, -0.3301, -0.5084]],

        [[-0.6080, -0.1151,  0.9069],
         [ 0.0667, -2.0047,  0.9373],
         [-0.2941, -0.9568, -0.8796],
         [ 1.8351,  0.1891, -0.1328]],

        [[ 2.3450,  1.0276, -0.0593],
         [-0.7225, -1.1913,  1.1319],
         [-0.8898, -0.0859,  0.6409],
         [-0.5624,  1.2657,  2.0325]]])
********  b
tensor([[-0.0808, -0.4589,  0.4824],
        [-0.2722, -0.1824, -1.2119],
        [ 1.0293,  1.0540,  0.2618],
        [ 1.5752,  0.0859, -1.9145]])
********  c
tensor([[[-0.0808, -0.4589,  0.4824],
       

# Tensor 加法和减法

In [79]:
import torch

# 这两个Tensor加减乘除会对b自动进行Broadcasting
a = torch.rand(3, 4)
b = torch.rand(4)

c1 = a + b
c2 = torch.add(a, b)
print(c1.shape, c2.shape)
print(torch.all(torch.eq(c1, c2)))

torch.Size([3, 4]) torch.Size([3, 4])
tensor(True)


# Tensor 乘法和除法

*, torch.mul, torch.mm, torch.matmul

参考: [torch.Tensor的4种乘法](https://blog.csdn.net/da_kao_la/article/details/87484403)

除法可以用乘法 API 完成。

## 广播机制

在 Tensor 的加减运算中，当两个 tensor 不能直接符合数学的运算规则时，PyTorch 会先尝试将 tensor 进行变换，再进行计算，这个变换的规则就是：broadcasting。

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

![](../../assets/book/screenshot_20260415115755.png)

在大多数情况下，我们将沿着数组中长度为1的轴进行广播，如下例子：

更多 [broadcasting 机制的介绍](https://zhuanlan.zhihu.com/p/2027421557199258948)。

In [76]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。
我们将两个矩阵*广播*为一个更大的$3\times2$矩阵，如下所示：矩阵`a`将复制列，
矩阵`b`将复制行，然后再按元素相加。


In [77]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 更多运算

更多加法和其他运算，参考[Pytorch Tensor基本数学运算](https://blog.csdn.net/weicao1990/article/details/93738722)：

* 减法运算
* 哈达玛积(对应元素相乘，也称为 element wise)
* 除法运算
* 幂运算
* 开方运算
* 指数与对数运算
* 近似值运算
* 裁剪运算

# 延申阅读

* [Tensor Broadcasting under the hood](https://medium.com/@harshit158/tensor-broadcasting-under-the-hood-16b95970ca0c)
* [Mastering PyTorch Indexing: Simple Techniques with Practical Examples](https://medium.com/@AI-Simplified/mastering-pytorch-indexing-simple-techniques-with-practical-examples-154c232b6d84)
* [torch.Tensor的4种乘法](https://blog.csdn.net/da_kao_la/article/details/87484403)
* [Pytorch Tensor基本数学运算](https://blog.csdn.net/weicao1990/article/details/93738722)
