# 理解 shape, stride, storage, view，is_contiguous 和 reshape 操作

https://zhuanlan.zhihu.com/p/2027415418696902203

https://medium.com/swlh/deep-learning-with-pytorch-tensor-basics-part-1-stride-offset-contiguous-tensors-5d87476b7d9f

![](../../assets/book/screenshot_20260419132906.png)



In [2]:
a = [1.0, 2.0, 1.0]

In [3]:
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [2]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6) # <1>
print(points)
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0


tensor([0., 0., 0., 0., 0., 0.])


In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])

## Storage

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_28244\3297796694.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

In [20]:
points.storage()[1]

1.0

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

In [25]:
points.stride()

(2, 1)

In [26]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [27]:
second_point.storage_offset()

2

## Stride
[“Stride” is a property of a tensor that determines how many elements should be skipped over in the storage array in order to get the next element in a given dimension in the original tensor! ](https://medium.com/swlh/deep-learning-with-pytorch-tensor-basics-part-1-stride-offset-contiguous-tensors-5d87476b7d9f)

In [28]:
second_point.stride()

(1,)

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [30]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [33]:
id(points.storage()) == id(points_t.storage())

True

In [34]:
points.stride()

(2, 1)

In [35]:
points_t.stride()

(1, 2)

## 转置

In [36]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [37]:
transpose_t.shape

torch.Size([5, 4, 3])

In [38]:
some_t.stride()

(20, 5, 1)

In [39]:
transpose_t.stride()

(1, 5, 20)

In [40]:
points.is_contiguous()

True

In [41]:
points_t.is_contiguous()

False

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [43]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [44]:
points_t.stride()

(1, 2)

In [45]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [46]:
points_t_cont.stride()

(3, 1)

In [47]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [48]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [49]:
short_points.dtype

torch.int16

In [50]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [51]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [52]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [53]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [54]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [55]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [57]:
points = torch.from_numpy(points_np)

In [58]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [59]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [60]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [61]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [62]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [63]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [64]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [65]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [66]:
points_gpu = points.to(device='cuda')

In [67]:
points_gpu = points.to(device='cuda:0')

In [68]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [69]:
points_gpu = points_gpu + 4

In [70]:
points_cpu = points_gpu.to(device='cpu')

In [71]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [72]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [73]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [74]:
a = torch.ones(3, 2)

In [75]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 张量连续性质 contiguous

张量连续：就是从一个元素访问下一个元素的时候，不需要跳跃。[If we move along a single row in this tensor, the elements are placed as in its storage and we do not have to jump over any number. A tensor like this is called “contiguous”. ](https://medium.com/swlh/deep-learning-with-pytorch-tensor-basics-part-1-stride-offset-contiguous-tensors-5d87476b7d9f)

https://medium.com/swlh/deep-learning-with-pytorch-tensor-basics-part-1-stride-offset-contiguous-tensors-5d87476b7d9f

https://stackoverflow.com/questions/48915810/what-does-contiguous-do-in-pytorch

* 使用张量的 `is_contiguous()` 接口，会返回一个张量是否连续。
* 使用张量的 `contiguous()` 接口，会将一个张量变成需连续的。
* 进行 narrow(), view(), expand(), transpose() 等操作要求 Tensor 是连续的。

# 索引 indexing
Tensor 的索引类似于 Python List 的索引和分片。

比如一个 AxBxC 的三个维度的 Tensor a。

a[第0维的分片, 第1维的分片, 第2维的分片]

分片的语法和 Python List 分片语法一致，开始:结束:步进。

更多索引的[高级语法介绍](https://medium.com/@AI-Simplified/mastering-pytorch-indexing-simple-techniques-with-practical-examples-154c232b6d84)。

In [76]:
print("*" * 8, " a")
a = torch.randn(5,4,3)
print(a)

print("*" * 8, " b")
b = a[1,]     # 只要第 0 维的第一个成员
print(b)

print("*" * 8, " c")
c = a[1:]   # 第 0 维从第一个成员开始都要，注意：这里索引从 0 开始
print(c)

print("*" * 8, " d")
d = a[1:, 1] # 第 0 维从第一个成员开始都要，第二维只要第一个成员
print(d)

********  a
tensor([[[ 0.4950, -0.0891, -0.4054],
         [ 0.9096,  0.9623, -1.1039],
         [-0.4138,  1.1651, -0.4606],
         [-1.5819, -0.1452, -0.6719]],

        [[ 0.7722,  0.5815,  0.3300],
         [-1.5880,  1.1257,  0.7854],
         [-0.6540, -0.1156,  1.0314],
         [ 0.0239, -0.7359,  1.0021]],

        [[ 0.4760, -0.0291,  0.0937],
         [-1.1843, -0.4385, -1.7915],
         [ 1.4929,  0.7014,  0.2411],
         [ 0.0092,  1.8437, -1.6901]],

        [[ 0.1222,  2.8245, -2.3270],
         [ 0.4414,  0.6516, -0.6353],
         [ 1.2201,  2.3616,  1.3563],
         [ 0.7274,  0.5663, -0.1346]],

        [[ 2.2032, -0.7478, -1.4483],
         [ 0.7857,  0.2120,  0.6412],
         [ 1.0652, -0.3829,  0.2626],
         [-0.4710, -0.2466,  1.2174]]])
********  b
tensor([[ 0.7722,  0.5815,  0.3300],
        [-1.5880,  1.1257,  0.7854],
        [-0.6540, -0.1156,  1.0314],
        [ 0.0239, -0.7359,  1.0021]])
********  c
tensor([[[ 0.7722,  0.5815,  0.3300],
       

# Tensor 加法和减法

In [77]:
import torch

# 这两个Tensor加减乘除会对b自动进行Broadcasting
a = torch.rand(3, 4)
b = torch.rand(4)

c1 = a + b
c2 = torch.add(a, b)
print(c1.shape, c2.shape)
print(torch.all(torch.eq(c1, c2)))

torch.Size([3, 4]) torch.Size([3, 4])
tensor(True)


# Tensor 乘法和除法

*, torch.mul, torch.mm, torch.matmul

除法可以用乘法 API 完成。

## 广播机制

在 Tensor 的加减运算中，当两个 tensor 不能直接符合数学的运算规则时，PyTorch 会先尝试将 tensor 进行变换，再进行计算，这个变换的规则就是：broadcasting。

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

![](../../assets/book/screenshot_20260415115755.png)

**在大多数情况下，我们将沿着数组中长度为1的轴进行广播**，如下例子：



In [78]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于`a`和`b`分别是$3\times1$和$1\times2$矩阵，如果让它们相加，它们的形状不匹配。
我们将两个矩阵*广播*为一个更大的$3\times2$矩阵，如下所示：矩阵`a`将复制列，
矩阵`b`将复制行，然后再按元素相加。




In [79]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

更多 [broadcasting 机制的介绍](https://zhuanlan.zhihu.com/p/2027421557199258948)。

## 乘法运算

torch.tensor 有四种乘法运算，分别是：*, torch.mul, torch.mm, torch.matmul.

### 点乘( * 或 torch.mul )

a与b做*乘法，原则是如果a与b的 size 不同，则以某种方式将a或b进行复制，使得复制后的a和b的size相同，然后再将a和b做 **按元素运算（element-wise）** 的乘法。




In [8]:
a = torch.randn(3,4)
b = torch.randn(3,4)
c = a * b
print(c)

d = torch.mul(a,b)
print(d)



tensor([[-0.6136, -0.1371, -0.7406,  0.2628],
        [ 2.4233, -0.3356,  0.4573, -0.3087],
        [-1.8804, -0.1781, -0.0034,  0.0309]])
tensor([[-0.6136, -0.1371, -0.7406,  0.2628],
        [ 2.4233, -0.3356,  0.4573, -0.3087],
        [-1.8804, -0.1781, -0.0034,  0.0309]])


如果是一个矩阵 和 一个标量相乘，则是，每个矩阵的元素都和该标量相乘得到新的 矩阵。

如果是一个矩阵 A 和一个向量 b 相乘，那么，进行广播操作。
但是要求，向量的列，和矩阵的列是一致的。
广播操作的原理是，此时是将向量复制多行，得到矩阵 B，复制后和矩阵 A 形状一样。

In [5]:
a = torch.ones(3,4)
b = torch.Tensor([1,2,3,4])


c = a * b
print(c.shape, a.shape)

print(c)
print("*" * 8, a)


torch.Size([3, 4]) torch.Size([3, 4])
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])
******** tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


如果是一个矩阵，和另外一个矩阵相乘。

那么，也是看形状是否一致，不一致，再进行广播，运算。
广播后，也可能无法运算，则会报错。

In [7]:
a = torch.randn(3,4,1)
b = torch.randn(4,1)
c = a*b
print(c)
print(c.shape)

tensor([[[-1.7898],
         [ 0.2617],
         [-0.1171],
         [-0.0473]],

        [[ 1.9004],
         [ 1.1876],
         [ 0.9173],
         [ 0.0523]],

        [[-0.9387],
         [-0.7067],
         [ 0.2133],
         [ 0.1355]]])
torch.Size([3, 4, 1])


### 标准矩阵乘法（torch.mm）

数学里的矩阵乘法，要求两个Tensor的维度满足矩阵乘法的要求，即第一个矩阵的列，必须等于第二个矩阵的行。

* 不支持广播
* 只接受矩阵，向量；不支持二维以上输入

In [9]:
a = torch.ones(3,4)
b = torch.ones(4,2)
c = torch.mm(a,b)
print(c)
print(c.shape)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
torch.Size([3, 2])


### 支持广播的矩阵乘法（torch.matmul）

torch.matmul 是 PyTorch 中用于执行矩阵乘法的函数，它根据输入张量的维度自动选择适当的矩阵乘法方式，包括：

* 向量内积（1D @ 1D）
* 矩阵乘向量（2D @ 1D）
* 向量乘矩阵（1D @ 2D）
* 矩阵乘矩阵（2D @ 2D）
* 批量矩阵乘法（>2D）

torch.mm的高级版本，支持多维，自动 broadcast。


In [11]:
a = torch.randn(3,4)
b = torch.randn(5,4,2)
c = torch.matmul(a, b)
print(c)
print(c.shape)

tensor([[[ 1.3637, -4.4076],
         [ 1.9177,  0.7140],
         [-8.7800,  5.3487]],

        [[ 2.9100, -1.0085],
         [-0.1696, -0.6489],
         [-1.2021,  3.8336]],

        [[ 2.4433, -5.1747],
         [-1.5190,  5.2143],
         [ 1.2871,  3.6648]],

        [[-0.9505,  7.6072],
         [ 0.6410, -0.9118],
         [ 7.2743, -2.6647]],

        [[ 1.5914, -0.0501],
         [ 1.3706,  2.2338],
         [-1.2830,  2.0154]]])
torch.Size([5, 3, 2])


更多介绍：https://www.cnblogs.com/ljbguanli/p/18990139

# 更多运算

更多加法和其他运算，参考[Pytorch Tensor基本数学运算](https://blog.csdn.net/weicao1990/article/details/93738722)：

* 减法运算
* 哈达玛积(对应元素相乘，也称为 element wise)
* 除法运算
* 幂运算
* 开方运算
* 指数与对数运算
* 近似值运算
* 裁剪运算

# 延申阅读

* [Tensor Broadcasting under the hood](https://medium.com/@harshit158/tensor-broadcasting-under-the-hood-16b95970ca0c)
* [Mastering PyTorch Indexing: Simple Techniques with Practical Examples](https://medium.com/@AI-Simplified/mastering-pytorch-indexing-simple-techniques-with-practical-examples-154c232b6d84)
* [torch.Tensor的4种乘法](https://blog.csdn.net/da_kao_la/article/details/87484403)
* [Pytorch Tensor基本数学运算](https://blog.csdn.net/weicao1990/article/details/93738722)
